// Copyright 2023
// This file is automatically generated by CMake
// Only for DataCacheCenter shared library

#pragma once

#define DCC_VERSION_MAJOR 0
#define DCC_VERSION_MINOR 0
#define DCC_VERSION_PATCH 1
